### ISSUE TITLE
duplicated method in card component 

### ISSUE THREAD

**Issue by mzbac** [romainberger/react-portal-tooltip#48]
@romainberger 
CheckWindowPosition, getStyle methods are duplicated in source code

**Comment by Redmega** [comment]
`checkWindowPosition` is [here (L256)](https://github.com/romainberger/react-portal-tooltip/blob/master/src/index.js#L256) and [here (L384)](https://github.com/romainberger/react-portal-tooltip/blob/master/src/index.js#L384). Looks like the one on L256 is newer as it is checking for the `arrow` prop

`getStyle` is completely duplicate, no difference, on [L167](https://github.com/romainberger/react-portal-tooltip/blob/master/src/index.js#L167) and [L295](https://github.com/romainberger/react-portal-tooltip/blob/master/src/index.js#L295)

**Comment by tanqhnguyen** [comment]
Since the later has been in production for while some time and no problem so far, I think we can safely remove https://github.com/romainberger/react-portal-tooltip/blob/master/src/index.js#L256

**Comment by Redmega** [comment]
Hmm... What about references to the `arrow` property? Haven't gotten a chance to see what the differences really are.

**Comment by tanqhnguyen** [comment]
It is used to change the position of the arrow when the tooltip is shown near the edge of the screen (style.left condition)

With the offset
<img width="183" alt="screen shot 2017-08-29 at 11 15 49 pm" src="https://user-images.githubusercontent.com/910024/29842017-314ab912-8d10-11e7-9908-72bd316e8487.png">

Without the offset
<img width="173" alt="screen shot 2017-08-29 at 11 16 03 pm" src="https://user-images.githubusercontent.com/910024/29842025-3b88d51c-8d10-11e7-87f8-44e5466733b5.png">

I prefer the later since it doesn't depend on any fixed number (`10` in this case)

**Comment by Redmega** [comment]
Hmm... It looks like those are `arrow="center"` vs `arrow="right"` though, isn't it? Or are those the exact same arrow prop value?

I'll do some tests later today if I get time at work...

**Comment by Redmega** [comment]
Closed in #51
